import type { ClassEntry } from './definitions';

export const classEntries: ClassEntry[] = [
  {
    id: '1',
    date: 'Wednesday, January 1, 2025',
    scheduledTime: '8:00 PM',
    entryTime: '7:21 PM',
    slideQAC: '7:14 PM',
    classStartTime: '8:01 PM',
    productType: 'English [Online] Promotional Class',
    course: 'OB 25 X SEJ',
    subject: 'English',
    topic: 'N/A',
    teacher1: 'Rifah Salsabil',
    teacher2: 'Eyamim Sultana',
    teacher3: '',
    studio: 'Studio 7 - NB6',
    studioCoordinator: 'Refat',
    opsStakeholder: 'Hasib',
    lectureSlide: '',
    title: 'মজায় মজায় ইংরেজি শিখি!',
    caption:
      '🥳 Happy New year, সবাইকে! বছরের ১ম দিনেই পড়তে বসতে বলবো না! তবে আমাদের সাথে এই মজার গেইম খেলতে খেলতে শেখা যাবে ইংরেজি!',
    crossPost:
      'Crosspost Platform: 10MS Skills Page, 10MS EC Page\nGroup: \nSEJ Free Group\n"Groups\nClass 6 Super Students | 10MS\nClass 7 Super Students | 10MS\nClass 8 Super Students | 10MS\nClass 9 Super Students | 10MS\nClass 6-10 Super Students | 10MS\n10 Minute School Live\nAS Group\nMS Group"',
    sourcePlatform: '10 MS Official Page + 10 MS 1- 12 YT',
    teacherConfirmation: '',
    zoomLink: '',
    zoomCredentials: '-',
    moderatorLink:
      'https://drive.google.com/file/d/1kF-gN8z1Qr1vygV7odALFN2xJJECj4KC/view?usp=sharing',
    annotatedSlideLink: 'N/A',
    classStopTimestamps: '0',
    startDelayMinutes: '65',
    totalDurationMinutes: '219',
    viewCount10Min: '173',
    viewCount40_50Min: '149',
    viewCountBeforeEnd: '298',
    highestAttendance: '181',
    averageAttendance: '1551',
    totalComments: '1.2k',
    classLink: 'https://fb.watch/wR6h_JjrDk/',
    recordingLink: 'N/A',
    classQACFeedback: '',
    remarks: '',
  },
  {
    id: '2',
    date: 'Wednesday, January 1, 2025',
    scheduledTime: '7:00 PM',
    entryTime: 'N/A',
    slideQAC: 'N/A',
    classStartTime: 'N/A',
    productType: 'English [Online] Promotional Class',
    course: 'SEJ LIVE Batch [Free]',
    subject: 'English',
    topic: 'Spoken English Junior LIVE Batch | Free Class',
    teacher1: 'Nusrat Bintay Haider',
    teacher2: '',
    teacher3: '',
    studio: "Instructor's Home",
    studioCoordinator: 'Refat',
    opsStakeholder: 'Nafish',
    lectureSlide: '',
    title: '',
    caption: '',
    crossPost: 'Zoom',
    sourcePlatform: '',
    teacherConfirmation: 'https://10ms.io/SEJ-Freeclass',
    zoomLink: '',
    zoomCredentials: '-',
    moderatorLink: 'N/A',
    annotatedSlideLink: 'N/A',
    classStopTimestamps: '-',
    startDelayMinutes: '-',
    totalDurationMinutes: '-',
    viewCount10Min: '-',
    viewCount40_50Min: '-',
    viewCountBeforeEnd: '-',
    highestAttendance: '-',
    averageAttendance: '-',
    totalComments: '-',
    classLink: 'N/A',
    recordingLink: '',
    classQACFeedback: '',
    remarks: '',
  },
  {
    id: '3',
    date: 'Wednesday, January 1, 2025',
    scheduledTime: '4:00 PM',
    entryTime: '3:58 PM',
    slideQAC: '4:07 PM',
    classStartTime: '4:15 PM',
    productType: 'OB Promotional Class',
    course: 'OB 2025',
    subject: 'N/A',
    topic: 'Results Feedback Live',
    teacher1: 'Sajan Chakraborty',
    teacher2: '',
    teacher3: '',
    studio: 'Studio 7 - NB6',
    studioCoordinator: 'Joy',
    opsStakeholder: 'Abdullah',
    lectureSlide: '',
    title: '🔴 LIVE: আমাদের স্টুডেন্টদের চমৎকার রেজাল্ট দিয়ে নতুন বছরের শুরু! 😇',
    caption:
      'বার্ষিক পরীক্ষায় আমাদের ক্লাস 6-9 এর স্টুডেন্টদের চমৎকার রেজাল্ট দিয়ে আমাদের নতুন বছরের শুরু! 🔥',
    crossPost: 'Class 6-9 All Groups, Class 6-10 Super Students',
    sourcePlatform: '10 MS Official Page',
    teacherConfirmation: '',
    zoomLink: '',
    zoomCredentials: 'N/A',
    moderatorLink: 'N/A',
    annotatedSlideLink: 'N/A',
    classStopTimestamps: '15',
    startDelayMinutes: '40',
    totalDurationMinutes: '161',
    viewCount10Min: '178',
    viewCount40_50Min: '151',
    viewCountBeforeEnd: '188',
    highestAttendance: '164',
    averageAttendance: '472',
    totalComments: '453',
    classLink: 'https://fb.watch/wR5BQpK_Pe/',
    recordingLink: 'N/A',
    classQACFeedback: '',
    remarks: '',
  },
  {
    id: '4',
    date: 'Wednesday, January 1, 2025',
    scheduledTime: '6:00 PM',
    entryTime: '5:19 PM',
    slideQAC: '5:53 PM',
    classStartTime: '6:02 PM',
    productType: 'HSC Launching LIVE',
    course: 'HSC 25 SMP (Humanities)',
    subject: 'N/A',
    topic: 'HSC 25 SMP Orientation & Launching Live: Humanities',
    teacher1: 'Farhan Sakib',
    teacher2: 'Mahbubul Newaz Farsim, MR.Jafar Imam, Md. Abdul Kader Nihaj',
    teacher3: 'Jannatul Bushra, Al Rabby Siemens',
    studio: 'Studio 5 - NB6',
    studioCoordinator: 'Refat',
    opsStakeholder: 'Abdullah',
    lectureSlide: '',
    title: '🔴 LIVE: HSC 25 ব্যাচের শেষ ৫ মাসের A+ এর গেইমপ্ল্যান 🔥 (মানবিক বিভাগ)',
    caption:
      "HSC'25 ব্যাচ, শেষ ৫ মাসে A+ পাওয়ার গেইমপ্ল্যান শেয়ার করবো আজকে তোমাদের সাথে। 🔥(মানবিক বিভাগ) \nShare the Live. \nশেষ মুহূর্তের A+ প্রস্তুতি নিশ্চিত করতে ক্লিক করো কমেন্টে অথবা কল করো 16910 এই নম্বরে। 📞",
    crossPost:
      'Group\n10MS SSC HSC Students \nHSC 25 Free A+ Suggestions\n10 Minute School LIVE\nAS Groups \nMS Groups',
    sourcePlatform: '10 MS Official Page and 10 Minute School Admissions',
    teacherConfirmation:
      'Teacher 1: Confirmed\nTeacher 2: Confirmed\nTeacher 3: Called twice (No Response)\nTeacher 4: Confirmed\nTeacher 5: Confirmed\nTeacher 6: Busy',
    zoomLink: '',
    zoomCredentials: '',
    moderatorLink: 'N/A',
    annotatedSlideLink:
      'https://drive.google.com/file/d/1T1oUH-BifaiHNAUv_ileBAGoIGznsQqT/view?usp=sharing',
    classStopTimestamps: 'N/A',
    startDelayMinutes: '2',
    totalDurationMinutes: '40',
    viewCount10Min: '207',
    viewCount40_50Min: '183',
    viewCountBeforeEnd: '174',
    highestAttendance: '338',
    averageAttendance: '188',
    totalComments: '394',
    classLink: 'https://fb.watch/wR6tfIg27D/',
    recordingLink: 'N/A',
    classQACFeedback: '',
    remarks: '',
  },
  {
    id: '5',
    date: 'Wednesday, January 1, 2025',
    scheduledTime: '8:30 PM',
    entryTime: '7:54 PM',
    slideQAC: '8:14 PM',
    classStartTime: '8:33 PM',
    productType: 'SSC Promotional Class',
    course: 'SSC 25 One Shot',
    subject: 'Bangla 1st Paper',
    topic:
      'SSC 2024 One Shot MCQ |Bangla 1st Paper | Board Question Solving | Barisal Board 2024, Chattogram Board 2024, Jessore Board 2024 |',
    teacher1: 'Farhan Sakib',
    teacher2: '',
    teacher3: '',
    studio: 'Studio 1 - HQ1',
    studioCoordinator: 'Joy',
    opsStakeholder: 'Hasib',
    lectureSlide: '',
    title:
      '🔴 SSC 25 LIVE: বাংলা ১ম পত্র - বরিশাল, চট্টগ্রাম, যশোর - বোর্ড প্রশ্ন সমাধান (২০২৪) 🔥',
    caption:
      '🔴 SSC 25 ব্যাচের বাংলা ১ম পত্র বোর্ড প্রশ্ন সমাধান (২০২৪) \n👨‍🏫  ফারহান ভাইয়া (বাংলা টিচার)\n📚 বরিশাল, চট্টগ্রাম, যশোর বোর্ড\nShare the LIVE. 😃\nSSC 25 এর শেষ মুহূর্তের A+ প্রস্তুতি নিতে এখনই ক্লিক করো কমেন্টে দেওয়া লিংকে। বিস্তারিত জানতে কল করো 16910 এই নম্বরে।',
    crossPost:
      'Groups\n10MS SSC HSC Group\nSSC 25 Free A+ Suggestions\n10 Minute School Live\nAS Group\nMS Group',
    sourcePlatform:
      '10MS Main page+10 MS 1-12 YT and SSC 25 Free A+ Suggestions + SSC 2025 শেষ মুহূর্তের প্রস্তুতি কোর্স [বিজ্ঞান বিভাগ] + SSC 2025 শেষ মুহূর্তের প্রস্তুতি কোর্স [ব্যবসায় শিক্ষা বিভাগ] + SSC 2025 শেষ মুহূর্তের প্রস্তুতি কোর্স [মানবিক বিভাগ]',
    teacherConfirmation: '',
    zoomLink: '',
    zoomCredentials: 'N/A',
    moderatorLink:
      'https://drive.google.com/file/d/1EtX2okefmsf_pn-pVbkB8fXTR2JXubIx/view?usp=sharing',
    annotatedSlideLink: 'N/A',
    classStopTimestamps: '8',
    startDelayMinutes: '93',
    totalDurationMinutes: '175',
    viewCount10Min: '184',
    viewCount40_50Min: '137',
    viewCountBeforeEnd: '210',
    highestAttendance: '180',
    averageAttendance: '623',
    totalComments: '1.2k',
    classLink: 'https://fb.watch/wR40TD8ZSs/',
    recordingLink: 'N/A',
    classQACFeedback: '',
    remarks: '',
  },
  {
    id: '6',
    date: 'Wednesday, January 1, 2025',
    scheduledTime: '6:30 PM',
    entryTime: '6:26 PM',
    slideQAC: '6:15 PM',
    classStartTime: '6:26 PM',
    productType: 'OB Promotional & Paid Class',
    course: 'OB 2025',
    subject: 'N/A',
    topic: '১০ মিনিট স্কুল অ্যাপ: তোমার A+ পাওয়ার গোপন হাতিয়ার!',
    teacher1: 'Sajan Chakraborty',
    teacher2: '',
    teacher3: '',
    studio: 'Studio 4 - NB6',
    studioCoordinator: 'Refat',
    opsStakeholder: 'Abdullah',
    lectureSlide: '',
    title: '',
    caption: '',
    crossPost: '10 MS Official Page + 10 MS 1- 12 YT',
    sourcePlatform: '',
    teacherConfirmation: '',
    zoomLink: 'N/A',
    zoomCredentials:
      'https://drive.google.com/file/d/1UpR3AVtJZYledgU05BVldo-jfTYnUmoj/view?usp=sharing',
    moderatorLink: 'N/A',
    annotatedSlideLink: '-',
    classStopTimestamps: '-',
    startDelayMinutes: '-',
    totalDurationMinutes: '-',
    viewCount10Min: '-',
    viewCount40_50Min: '-',
    viewCountBeforeEnd: '-',
    highestAttendance: '-',
    averageAttendance: '-',
    totalComments: 'N/A',
    classLink: 'N/A',
    recordingLink: '',
    classQACFeedback: '',
    remarks: '',
  },
  {
    id: '7',
    date: 'Wednesday, January 1, 2025',
    scheduledTime: '5:00 PM',
    entryTime: '4:03 PM',
    slideQAC: '4:41 PM',
    classStartTime: '5:03 PM',
    productType: 'SSC Paid Class',
    course: 'SSC 25 SMP (Science)',
    subject: 'General Math',
    topic: 'অধ্যায় (৩): বীজগাণিতিক রাশি',
    teacher1: 'S M Shoumik Ahmed',
    teacher2: 'Nadiatul Swargo',
    teacher3: '',
    studio: 'Studio 1 - HQ1',
    studioCoordinator: 'Joy',
    opsStakeholder: 'Hasib',
    lectureSlide:
      'https://10minuteschoolsmd-my.sharepoint.com/:p:/g/personal/smd_10minuteschoolsmd_onmicrosoft_com/EStHIqhFx9NBvoV_QDs5W9wBnsqn5gSYN4PJfHkPatVIlQ?e=hoqguF',
    title: '▶SSC 2025 | General Math | অধ্যায় (৩): বীজগাণিতিক রাশি',
    caption:
      '▶SSC 2025 | General Math | অধ্যায় (৩): বীজগাণিতিক রাশি \n\n👨‍🏫 Instructor: Shoumik Ahmed\n\nClass Feedback Form: https://forms.gle/n5JGP196EbuV5cx29',
    crossPost: 'SSC 2025 শেষ মুহূর্তের প্রস্তুতি কোর্স [বিজ্ঞান বিভাগ]',
    sourcePlatform: '',
    teacherConfirmation: '',
    zoomLink: 'N/A',
    zoomCredentials:
      'https://drive.google.com/file/d/1BwVMYuliZlluNqZ8EcCrp3VqjyghtrhW/view?usp=sharing',
    moderatorLink: 'N/A',
    annotatedSlideLink: '8',
    classStopTimestamps: '185',
    startDelayMinutes: '432',
    totalDurationMinutes: '575',
    viewCount10Min: '473',
    viewCount40_50Min: '591',
    viewCountBeforeEnd: '494',
    highestAttendance: '8777',
    averageAttendance: '6.9K',
    totalComments: '4.8k',
    classLink: 'https://fb.watch/wQUpi2PKSG/',
    recordingLink: 'N/A',
    classQACFeedback: '',
    remarks: '',
  },
  {
    id: '8',
    date: 'Wednesday, January 1, 2025',
    scheduledTime: '5:00 PM',
    entryTime: '4:03 PM',
    slideQAC: '4:41 PM',
    classStartTime: '5:03 PM',
    productType: 'SSC Paid Class',
    course: 'SSC 25 SMP (Arts)',
    subject: 'General Math',
    topic: 'অধ্যায় (৩): বীজগাণিতিক রাশি',
    teacher1: 'S M Shoumik Ahmed',
    teacher2: 'Nadiatul Swargo',
    teacher3: '',
    studio: 'Studio 1 - HQ1',
    studioCoordinator: 'Joy',
    opsStakeholder: 'Hasib',
    lectureSlide:
      'https://10minuteschoolsmd-my.sharepoint.com/:p:/g/personal/smd_10minuteschoolsmd_onmicrosoft_com/EStHIqhFx9NBvoV_QDs5W9wBnsqn5gSYN4PJfHkPatVIlQ?e=hoqguF',
    title: '▶SSC 2025 | General Math | অধ্যায় (৩): বীজগাণিতিক রাশি',
    caption:
      '▶SSC 2025 | General Math | অধ্যায় (৩): বীজগাণিতিক রাশি \n\n👨‍🏫 Instructor: Shoumik Ahmed\n\nClass Feedback Form: https://forms.gle/n5JGP196EbuV5cx29',
    crossPost: 'SSC 2025 শেষ মুহূর্তের প্রস্তুতি কোর্স [মানবিক বিভাগ]',
    sourcePlatform: '',
    teacherConfirmation: 'ID: farhan@10minuteschool.com\nPass: #10MSJobs@2022',
    zoomLink: 'N/A',
    zoomCredentials:
      'https://drive.google.com/file/d/1BwVMYuliZlluNqZ8EcCrp3VqjyghtrhW/view?usp=sharing',
    moderatorLink: 'N/A',
    annotatedSlideLink: '8',
    classStopTimestamps: '185',
    startDelayMinutes: '68',
    totalDurationMinutes: '81',
    viewCount10Min: '61',
    viewCount40_50Min: '93',
    viewCountBeforeEnd: '70',
    highestAttendance: '2135',
    averageAttendance: '1.2k',
    totalComments: '495',
    classLink: 'https://fb.watch/wQUoA7TjWH/',
    recordingLink: 'N/A',
    classQACFeedback: '',
    remarks: '',
  },
  {
    id: '9',
    date: 'Wednesday, January 1, 2025',
    scheduledTime: '5:00 PM',
    entryTime: '4:03 PM',
    slideQAC: '4:41 PM',
    classStartTime: '5:03 PM',
    productType: 'SSC Paid Class',
    course: 'SSC 25 SMP (Commerce)',
    subject: 'General Math',
    topic: 'অধ্যায় (৩): বীজগাণিতিক রাশি',
    teacher1: 'S M Shoumik Ahmed',
    teacher2: 'Nadiatul Swargo',
    teacher3: '',
    studio: 'Studio 1 - HQ1',
    studioCoordinator: 'Joy',
    opsStakeholder: 'Hasib',
    lectureSlide:
      'https://10minuteschoolsmd-my.sharepoint.com/:p:/g/personal/smd_10minuteschoolsmd_onmicrosoft_com/EStHIqhFx9NBvoV_QDs5W9wBnsqn5gSYN4PJfHkPatVIlQ?e=hoqguF',
    title: '▶SSC 2025 | General Math | অধ্যায় (৩): বীজগাণিতিক রাশি',
    caption:
      '▶SSC 2025 | General Math | অধ্যায় (৩): বীজগাণিতিক রাশি \n\n👨‍🏫 Instructor: Shoumik Ahmed\n\nClass Feedback Form: https://forms.gle/n5JGP196EbuV5cx29',
    crossPost: 'SSC 2025 শেষ মুহূর্তের প্রস্তুতি কোর্স [ব্যবসায় শিক্ষা বিভাগ]',
    sourcePlatform: '',
    teacherConfirmation: '',
    zoomLink: 'N/A',
    zoomCredentials:
      'https://drive.google.com/file/d/1BwVMYuliZlluNqZ8EcCrp3VqjyghtrhW/view?usp=sharing',
    moderatorLink: 'N/A',
    annotatedSlideLink: '8',
    classStopTimestamps: '185',
    startDelayMinutes: '61',
    totalDurationMinutes: '85',
    viewCount10Min: '56',
    viewCount40_50Min: '91',
    viewCountBeforeEnd: '68',
    highestAttendance: '1137',
    averageAttendance: '789',
    totalComments: '356',
    classLink: 'https://fb.watch/wQUnW-_6QP/',
    recordingLink: 'N/A',
    classQACFeedback: '',
    remarks: '',
  },
];